---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: 'Cloning PGBlitz'
      git:
        repo: 'https://github.com/vFlagR/Install'
        dest: '/opt/pgstage'
        version: 'gce_no_nvme'
        force: yes
